server.port=8082
spring.application.name=ecommerce-app

# The AUTO_SERVER=TRUE is the key to stopping the locking error
spring.datasource.url=jdbc:h2:file:./data/shopdb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
# 1. Force Spring to run your data.sql
spring.sql.init.mode=always

# 3. This is the MOST IMPORTANT line: 
# It makes sure the tables are ready before the SQL inserts the 100+ items
spring.jpa.defer-datasource-initialization=true
